# Generated by Django 3.1.1 on 2020-10-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandardFit_down',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothType', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=5)),
                ('waistWidth', models.IntegerField()),
                ('totalHeight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StandardFit_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothType', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=5)),
                ('chest', models.IntegerField()),
                ('shoulder', models.IntegerField()),
                ('sleeve', models.IntegerField(blank=True, null=True)),
                ('clothGeneral', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UpCloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('multyFitType', models.ManyToManyField(to='cloth.StandardFit_up')),
            ],
        ),
        migrations.CreateModel(
            name='DownCloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('multyFitType', models.ManyToManyField(to='cloth.StandardFit_down')),
            ],
        ),
    ]
