# Generated by Django 3.1.2 on 2020-10-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='clothImage',
            field=models.ImageField(blank=True, null=True, upload_to='cloth/'),
        ),
    ]
