# Generated by Django 3.1.2 on 2020-10-25 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0005_auto_20201023_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='multyFitType',
        ),
        migrations.AddField(
            model_name='cloth',
            name='multyFitTypePants',
            field=models.ManyToManyField(null=True, to='cloth.StandardFit_down'),
        ),
        migrations.AddField(
            model_name='cloth',
            name='multyFitTypeSleeve',
            field=models.ManyToManyField(null=True, to='cloth.StandardFit_up'),
        ),
    ]
