# Generated by Django 3.1.2 on 2020-10-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0006_auto_20201025_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='multyFitTypePants',
            field=models.ManyToManyField(blank=True, null=True, to='cloth.StandardFit_down'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='multyFitTypeSleeve',
            field=models.ManyToManyField(blank=True, null=True, to='cloth.StandardFit_up'),
        ),
    ]
