# Generated by Django 3.1.2 on 2020-10-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0007_auto_20201025_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewofuser',
            name='users',
        ),
    ]
