# Generated by Django 3.1.2 on 2020-10-25 08:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0008_remove_viewofuser_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewofuser',
            name='product',
        ),
        migrations.AddField(
            model_name='viewofuser',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloth.cloth'),
            preserve_default=False,
        ),
    ]
