# Generated by Django 3.1.1 on 2020-10-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0003_remove_customuser_fit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='faceLength',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address1',
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='address2',
            field=models.TextField(default=30, max_length=20),
            preserve_default=False,
        ),
    ]
