# Generated by Django 3.1.1 on 2020-10-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0004_auto_20201024_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address2',
        ),
        migrations.AddField(
            model_name='customuser',
            name='faceLength',
            field=models.FloatField(default=22.9),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fit',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
